#!/usr/bin/env python

# This script submits a PBS script, as with 'qsub script.sh'
# and adds the job to the prisms_jobs.JobDB job database

import sys
import argparse

import prisms_jobs

parser = argparse.ArgumentParser(description='Submit a script and add to prisms_jobs database')
parser.add_argument('scriptname', type=str, nargs=1, help='Submit script')

if __name__ == "__main__":
    args = parser.parse_args()

    substr = open(args.scriptname, 'r').read()
    job = prisms_jobs.Job(substr=substr)
    job.submit()
